# Generated by Django 4.2.4 on 2023-09-03 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Candidatedirectory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=255, null=True)),
                ('last_name', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.CharField(blank=True, max_length=50, null=True)),
                ('recruiter_alert', models.CharField(blank=True, max_length=50, null=True)),
                ('role', models.IntegerField(blank=True, null=True)),
                ('contact_no_primary', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True)),
                ('contact_no_alternate', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True)),
            ],
            options={
                'db_table': 'candidate_directory',
            },
        ),
    ]
