# Generated by Django 4.2.4 on 2023-09-03 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('candidateapp', '0002_candidatedirectory_created_by_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='candidatedirectory',
            table='candidate_directory',
        ),
    ]
