# Generated by Django 4.2.4 on 2023-09-03 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('candidateapp', '0003_alter_candidatedirectory_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='city',
            name='candidate',
        ),
        migrations.RemoveField(
            model_name='educationlevel',
            name='candidate',
        ),
        migrations.RemoveField(
            model_name='educationqualification',
            name='candidate',
        ),
        migrations.RemoveField(
            model_name='educationspecialization',
            name='candidate',
        ),
        migrations.RemoveField(
            model_name='employeedirectory',
            name='candidate',
        ),
        migrations.RemoveField(
            model_name='eventdetails',
            name='candidate',
        ),
        migrations.RemoveField(
            model_name='experiencelevel',
            name='candidate',
        ),
        migrations.RemoveField(
            model_name='gender',
            name='candidate',
        ),
        migrations.RemoveField(
            model_name='jobrequisition',
            name='candidate',
        ),
        migrations.RemoveField(
            model_name='maritalstatus',
            name='candidate',
        ),
        migrations.RemoveField(
            model_name='persona',
            name='candidate',
        ),
        migrations.RemoveField(
            model_name='reasonforchange',
            name='candidate',
        ),
        migrations.RemoveField(
            model_name='screeningmode',
            name='candidate',
        ),
        migrations.RemoveField(
            model_name='source',
            name='candidate',
        ),
        migrations.RemoveField(
            model_name='sourcetype',
            name='candidate',
        ),
    ]
