# Generated by Django 4.2.4 on 2023-09-03 14:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('candidateapp', '0004_remove_city_candidate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidatedirectory',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='candidateapp.eventdetails'),
        ),
        migrations.AddField(
            model_name='candidatedirectory',
            name='job_position',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='candidateapp.jobrequisition'),
        ),
        migrations.AddField(
            model_name='candidatedirectory',
            name='persona',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='candidateapp.persona'),
        ),
        migrations.AddField(
            model_name='candidatedirectory',
            name='screening_mode',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='candidateapp.screeningmode'),
        ),
    ]
