# Generated by Django 4.2.4 on 2023-09-03 15:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('candidateapp', '0005_candidatedirectory_event_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidatedirectory',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='candidateapp.city'),
        ),
        migrations.AddField(
            model_name='candidatedirectory',
            name='educational_level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='candidateapp.educationlevel'),
        ),
        migrations.AddField(
            model_name='candidatedirectory',
            name='employee_directory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='candidateapp.employeedirectory'),
        ),
        migrations.AddField(
            model_name='candidatedirectory',
            name='equ_qualification',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='candidateapp.educationqualification'),
        ),
        migrations.AddField(
            model_name='candidatedirectory',
            name='equ_specialization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='candidateapp.educationspecialization'),
        ),
        migrations.AddField(
            model_name='candidatedirectory',
            name='experience_level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='candidateapp.experiencelevel'),
        ),
        migrations.AddField(
            model_name='candidatedirectory',
            name='gender',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='candidateapp.gender'),
        ),
        migrations.AddField(
            model_name='candidatedirectory',
            name='marital_status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='candidateapp.maritalstatus'),
        ),
        migrations.AddField(
            model_name='candidatedirectory',
            name='reason_for_change',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='candidateapp.reasonforchange'),
        ),
        migrations.AddField(
            model_name='candidatedirectory',
            name='source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='candidateapp.source'),
        ),
        migrations.AddField(
            model_name='candidatedirectory',
            name='source_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='candidateapp.sourcetype'),
        ),
    ]
