# Generated by Django 4.2.4 on 2023-09-03 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidateapp', '0006_candidatedirectory_city_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidatedirectory',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='candidatedirectory',
            name='modified_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
